services:
  agent-server:
    volumes:
      - ./src/agents:/app/agents
      - ./src/schema:/app/schema
      - ./src/service:/app/service
      - ./src/agents:/app/agents
      - ./src/client:/app/client
      - ./src/core:/app/core
      - ./src/mindlab_clients:/app/mindlab_clients
      - ./src/tests:/app/tests

      - ./src/run_agent.py:/app/run_agent.py
      - ./src/run_service.py:/app/run_service.py
      - ./src/run_client.py:/app/run_client.py

      - ./requirements.txt:/app/requirements.txt
      - ./local-requirements.txt:/app/local-requirements.txt
      - ./local_modules:/app/local_modules

    ports:
      - "8080:80"
  
  streamlit-app:
    volumes:
      - ./src/client/:/app/client/
      - ./src/schema/:/app/schema/
      - ./src/streamlit_app.py:/app/streamlit_app.py

    ports:
      - "8501:8501"

  postgres:
    expose:
      - "5432"
    ports:
      - "${COMMAND_SERVER_PORT}:6666"
      - "${DATABASE_PORT}:5432"
    volumes:
      # Persist the data between container invocations
      - postgresVolume:/var/lib/postgresql/data

  data-server:
    ports:
      - "${DATA_SERVER_PORT}:80"
  
  query-server:
    ports:
      - "5001:80"

  redis-query:
    ports:
      - "6379:6379"

  redis-data:
    ports:
      - "6380:6379"
  
  experiment-importer:
    ports:
      - "${EXPERIMENT_IMPORTER_PORT}:80"
    volumes:
      - ./rds-experiments:/data

volumes:
  postgresVolume:
    driver: local