version: 2.1

orbs:
  mindlab: mindlab/circle-orb@1.7.1
  docker: circleci/docker@2.6.0

jobs:
  build-test-push:
    docker:
      - image: cimg/python:3.11
    steps:
      - mindlab/set-env:
          var_name: GOOGLE_PROJECT_ID
          value: ml-zoo-development
      - when:
          condition:
            or:
              - equal: [ development, << pipeline.git.branch >> ]
              - equal: [ staging, << pipeline.git.branch >> ]
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - mindlab/set-env:
                var_name: GOOGLE_PROJECT_ID
                value: ml-zoo-${CIRCLE_BRANCH}
      - mindlab/set-env:
          var_name: GOOGLE_COMPUTE_ZONE
          value: europe-west2-a
      - mindlab/docker-authenticate-google:
          key: GCLOUD_V4_STORAGE_KEY
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout 
      - run:
          name: make private env
          command: echo 'USE_FAKE_MODEL=true' > .private.env
      - run:
          name: Install submodule dependencies
          command: sh ./app init-modules      
      - run:
          name: build agent-server container
          command: sh ./app build
      - run:
          name: Startup containers
          command: sh ./app ci_up    
      - run:
          name: testing
          command: sh ./app test
      - when:
          condition:
            or:
              - equal: [ development, << pipeline.git.branch >> ]
              - equal: [ staging, << pipeline.git.branch >> ]
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - mindlab/tag-and-push-google:
                current-tag: mindlab/agent-server:local
                project-id: ml-zoo-${CIRCLE_BRANCH}
                image-name: agent-server

  update-infrastructure-repo:
    executor:
      docker/docker
    steps:
      - mindlab/update-infrastructure-repo:
          branch_name: ${CIRCLE_BRANCH}
          container_name: agent-server
          container_tag: ${CIRCLE_SHA1}

workflows:
  build-test-push-update:
    jobs:
      - build-test-push:
          context: 'GCLOUD OPERATIONS'
      - update-infrastructure-repo:
          filters:
            branches:
              only:
                - development
                - staging
                - master
          requires:
            - build-test-push